apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-manifests
spec:
  destination:
    namespace: kube-prom-stack
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 19.2.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
