apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argo-cd-icpxnaz9
spec:
  destination:
    namespace: mysql
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: bitnami/mysql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.0.27
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
